stages: [trigger_jenkins]

trigger:jenkins:
  stage: trigger_jenkins
  image: curlimages/curl:8.9.1
  rules:
    # 머지 후 dev/master로 "푸시"될 때만
    - if: '$CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "master")'
      when: on_success
    - when: never
  script: |
    CRUMB=$(curl -s -u "$JENKINS_USER:$JENKINS_API_TOKEN" "$JENKINS_URL/crumbIssuer/api/json" | jq -r '.crumb' )

    curl -X POST \
      -u "$JENKINS_USER:$JENKINS_API_TOKEN" \
      -H "Jenkins-Crumb: $CRUMB" \
      "$JENKINS_URL/job/$JENKINS_JOB_NAME/buildWithParameters" \
      --data-urlencode "token=$JENKINS_JOB_TOKEN" \
      --data-urlencode "BRANCH=$CI_COMMIT_BRANCH" \
      --data-urlencode "HEAD=$CI_COMMIT_SHA" \
      --data-urlencode "PREV=$CI_COMMIT_BEFORE_SHA" \
      --data-urlencode "REPO_URL=$CI_REPOSITORY_URL"
  variables:
    # GitLab → Jenkins 접속정보(프로젝트 CI/CD Variables에 정의해두기)
    JENKINS_URL: ${JENKINS_URL}
    JENKINS_JOB_NAME: ${JENKINS_JOB_NAME}
    # Jenkins > Job에서 설정한 trigger token
    JENKINS_JOB_TOKEN: ${JENKINS_JOB_TOKEN}
    # Jenkins 사용자/API 토큰
    JENKINS_USER: ${JENKINS_USER}
    JENKINS_API_TOKEN: ${JENKINS_API_TOKEN}
