[project]
name = "llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "accelerate>=1.11.0",
    "datasets==4.1.1",
    "fastapi>=0.120.2",
    "math-verify>=0.8.0",
    "matplotlib>=3.10.7",
    "peft>=0.17.1",
    "qdrant-client>=1.15.1",
    "trl>=0.24.0",
    "vllm==0.10.2",
    "wandb>=0.22.3",
]
