[project]
name = "llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.3"
dependencies = [
    "accelerate>=1.11.0",
    "fastapi>=0.119.0",
    "langchain>=1.0.3",
    "langchain-community>=0.4.1",
    "langchain-core>=1.0.2",
    "langchain-huggingface>=1.0.0",
    "langchain-mongodb>=0.7.1",
    "langchain-qdrant>=1.1.0",
    "peft>=0.17.1",
    "sentence-transformers>=5.1.2",
    "trl>=0.24.0",
    "vllm==0.10.2",
    "wandb>=0.22.3",
]
