spring:
    application:
        name: EcoPrompt

    datasource:
        url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}

    data:
        mongodb:
            uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}?authSource=admin
        redis:
            host: ${REDIS_HOST}
            port: ${REDIS_PORT}
            password: ${REDIS_PASSWORD}

springdoc:
    override-with-generic-response: false